name: PlayUs-AI CI/CD 파이프라인

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:  # 수동 실행 허용

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.15'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Create .env file from secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "~/fastapi-app"

      - name: Install dependencies and run FastAPI with nohup
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/fastapi-app
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
            if [ -f uvicorn.pid ]; then
              kill $(cat uvicorn.pid) || true
              rm uvicorn.pid
            else
              pkill -f "uvicorn" || true
            fi
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > ~/fastapi.log 2>&1 & echo $! > uvicorn.pid
