name: PlayUs-AI Test 파이프라인

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10.15'

      - name: Install dependencies and run tests
        run: |
          pip install -r requirements.txt
          pytest --maxfail=1 --disable-warnings -q